### ISSUE TITLE
Illegal Character Error

### ISSUE THREAD

**Issue by imswel** [anthonyraymond/joal#173] opened 2022-09-28 22:47 UTC
With this type of adress : "https://aaa.bbb.ccc/announce.php?authkey=52458|11885|WkL83k" I got an error "TORRENT WAS REJECTED BY SERVER: JAVA.NET.URISYNTAXEXCEPTION: ILLEGAL CHARACTER IN QUERY AT INDEX 48"

**Comment by laur89** [comment] 2022-09-29 10:04
Duplicate of #171

**Closed** 2022-11-02 12:25 UTC
